# install dependencies on the host

- name: Gathering facts
  setup:
    gather_subset: all

- name: Install dependencies
  tags: always
  become: yes
  apt:
    name: ['pt-transport-https', 'build-essential', 'ca-certificates', 'curl', 'git', 'python-pip','vim', 'python-setuptools']
    state: latest
    install_recommends: no
    update_cache: yes

- name: Update pip
  become: yes
  pip:
    name: ['pip']
    state: latest
# pip3 install --upgrade pip

# - name: Update pip3
#   become: yes
#   pip3:
#     name: ['pip3']
#     state: latest

# # pip3 install --upgrade pip3
