- hosts: WebServer

  environment:
    https_proxy: http://wwwproxy.unimelb.edu.au:8000
    http_proxy: http://wwwproxy.unimelb.edu.au:8000
    ftp_proxy: http://wwwproxy.unimelb.edu.au:8000
    no_proxy: localhost,127.0.0.1,127.0.1.1,172.17.0.2,172.17.0.3,172.17.0.4,ubuntu

  roles:
    - role: common
    - role: webInstall
    - role: docker